### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by Appassassin** [kangarko/Winter#1]
Hi! I'm very interested in this plugin. I was just wondering, After christmas is over would I be able to get rid of snow on the ground in normally non-cold biomes using the plugin?

**Comment by kangarko** [comment]
Hey,

yes, you can just use WorldEdit and run the command "//replacenear <radius around you> snow 0". For larger areas, you can also use FastAsyncWorldEdit extension to remove snow from millions of blocks from your map.

You can also disable each Christmas-related feature from Winter after Christmas.
