### ISSUE TITLE
🎈 Roadmap for Ideas and Suggestions

### ISSUE THREAD

**Issue by kangarko** [kangarko/Winter#1]
![roadmap](https://i.imgur.com/a3FOfvL.png)
<h3><p align="center">A List of Ideas and Suggested Features</p></h3>

_Due to small team and high demand on us we are at present not open for more features. There is no ETA. All features are consideration only._

## OVERALL

- [ ] Making an option that will only enable snow generation when it's actually snowing in game according to the natural weather cycle

**Comment by swim709** [comment]
Was really hoping to use this plugin on my 1.16.4 server this holiday season. Currently it seems to not support this version.

**Comment by kangarko** [comment]
We do support it. If you have problems open a separate issue and post me your startup log.

**Comment by kangarko** [comment]
We unfortunately had to put Winter on maintenance only due to other, bigger projects.
