### ISSUE TITLE
Feature request: Disable particles per player

### ISSUE THREAD

**Issue by TheoRetisch1** [kangarko/Winter#10]
Particles are causing fps drops. Not all the player have the hardware to handle the fancy little particle so it would be awesome if you could add a /snow-command to disable the particle per player. This would be also useful for people who get annoyed of the particles after some hours because they just want to build or need a clear vison for whatever they like to do.

**Comment by kangarko** [comment]
Thanks, added.

**Comment by TheoRetisch1** [comment]
Thank you really much :). Awesome that you thought of storing the settings, so that one can restart the server without problems. Love it!

**Comment by kangarko** [comment]
Cheers ! If you'd like to help out, you're very welcome to post a review on Spigot :)
