### ISSUE TITLE
Griefprevention compatibility 

### ISSUE THREAD

**Issue by ArnoPompio** [kangarko/Winter#10]
1) How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)
A lot of owners use GriefPrevention, and some players on these servers don't like the snow, even if it's decorative. (I don't understand myself why they don't like). 

2) What would happen if we won't implement this feature? How's your server being affected?
The players would stay angry :(

3) If suggesting something new - Can the old system be modified/improved instead?
Add a way to make the /claimflags nosnowform working by don't putting snow in the claim with this claimflag.

Thanks ! (btw, amazing work)

**Comment by kangarko** [comment]
Thank you for your suggestion!
