### ISSUE TITLE
Enhancement: Enhance the blocklist

### ISSUE THREAD

**Issue by mormoon** [kangarko/Winter#12]
Could you please enhance the "Do_Not_Place_On:" list to respect wildmarks.

Example:
Do_Not_Place_On:
-*_BUTTON
-*_FENCE
-*_BANNER
-*_STAIRS

My list is getting a bit long :)

**Comment by kangarko** [comment]
Thanks, added. Just out of curiosity please post me your list :)

**Comment by mormoon** [comment]
Tnx, for adding the enhancement!

Do_Not_Place_On:
    - ICE
    - BARRIER
    - FENCE
    - NETHER_FENCE
    - STEP
    - DOUBLE_STEP
    - WOOD_STEP
    - DOUBLE_STONE_SLAB2
    - AIR
    - TORCH
    - LONG_GRASS
    - DOUBLE_PLANT
    - YELLOW_FLOWER
    - SUGAR_CANE
    - STONE_BUTTON
    - WOOD_BUTTON
    - FENCE_GATE
    - SPRUCE_FENCE_GATE
    - BIRCH_FENCE_GATE
    - JUNGLE_FENCE_GATE
    - DARK_OAK_FENCE_GATE
    - ACACIA_FENCE_GATE
    - SPRUCE_FENCE
    - BIRCH_FENCE
    - JUNGLE_FENCE
    - DARK_OAK_FENCE
    - ACACIA_FENCE
    - WATER
    - CARPET
    - STATIONARY_WATER
    - WHEAT
    - WOOD_STAIRS
    - SIGN
    - WALL_SIGN
    - STANDING_BANNER
    - WALL_BANNER
    - ENDER_CHEST
    - DAYLIGHT_DETECTOR
    - DAYLIGHT_DETECTOR_INVERTED

**Comment by mormoon** [comment]
Compressed, with the new update;

    Do_Not_Place_On:
    - ICE
    - BARRIER
    - FENCE
    - FENCE_GATE
    - STEP
    - DOUBLE_STONE_SLAB2
    - AIR
    - TORCH
    - LONG_GRASS
    - DOUBLE_PLANT
    - YELLOW_FLOWER
    - SUGAR_CANE
    - BUTTON
    - WATER
    - CARPET
    - STATIONARY_WATER
    - WHEAT
    - STAIRS
    - SIGN
    - BANNER
    - ENDER_CHEST
    - DAYLIGHT_DETECTOR
    - DAYLIGHT_DETECTOR_INVERTED

**Comment by kangarko** [comment]
Thanks, btw this can be compressed even more :

    Do_Not_Place_On:
    - ICE
    - BARRIER
    - FENCE
    #- FENCE_GATE
    - STEP
    - SLAB
    - AIR
    - TORCH
    - LONG_GRASS
    - DOUBLE_PLANT
    - YELLOW_FLOWER
    - SUGAR_CANE
    - BUTTON
    - WATER
    - CARPET
    #- STATIONARY_WATER
    - WHEAT
    - STAIRS
    - SIGN
    - BANNER
    - ENDER_CHEST
    - DAYLIGHT_DETECTOR
    #- DAYLIGHT_DETECTOR_INVERTED

**Comment by kangarko** [comment]
Btw, the actual version has native checks to avoid following blocks:

![a](https://i.imgur.com/rYFsDZO.png)

Cheers!
