### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by ghost** [kangarko/Winter#12]
So I have the plugin installed and everything but when it loads it gives me this error:

 _   _                       _
| | | | ___   ___  _ __  ___| |
| |_| |/ _ \ / _ \| '_ \/ __| |
|  _  | (_) | (_) | |_) \__ \_|
|_| |_|\___/ \___/| .__/|___(_)
                     |_|
!-----------------------------------------------------!
Error loading Winter v1.1.7, plugin is disabled!
Running on 1.16.4-R0.1-SNAPSHOT (v1_16_R3) & Java 11.0.9
!-----------------------------------------------------!
Error: String index out of range: -3
!-----------------------------------------------------!

Please help

**Comment by kangarko** [comment]
Update winter.
