### ISSUE TITLE
No snow particles on version 1.8.8

### ISSUE THREAD

**Issue by GermanMinersNET** [kangarko/Winter#14]
On version 1.8.8, no snow particles are generated for players with default configs. @separatio can confirm it.

_Note: This is basically only a repost of issue #13 but contains necessary information as requested by separatio._

**Comment by separatio** [comment]
^ Right. I pretty much tested all possible variants of configuration to make sure. @kangarko confirmed it himself. This will be fixed asap. :slightly_smiling_face:

**Comment by kangarko** [comment]
See https://github.com/kangarko/Winter/issues/13

Will be fixed tonight + a bonus: compatibility down to 1.7.10 :)

Cheers!
