### ISSUE TITLE
Snow layers and NPCS - Suggestion

### ISSUE THREAD

**Issue by CrashOverrideMC** [kangarko/Winter#15]
I recently visited spawn where I have a few NPCs for shops that were starting to get buried. I have added an ignored block under each of them to stop this but in future version is there a way to detect NPCs and not add a snow layer to that area

**Comment by kangarko** [comment]
Hello,

great suggestion! I am having exams right now and this looks like complex code, so I have to delay it, sorry! But if you can provide an abstract idea of how the check would work more precisely I could possibly get to it or do some quick workaround. Thank you.
