### ISSUE TITLE
1.16.4: Snow layers in mid air

### ISSUE THREAD

**Issue by swim709** [kangarko/Winter#17]
In some areas, snow layers will accumulate in mid air. Any idea as to why this might be happening?
[Winter.zip](https://github.com/kangarko/Winter/files/5676095/Winter.zip)

**Comment by kangarko** [comment]
Not sure, but you can add all the AIR types under Terrain.Snow_Generation.Do_Not_Place_On such as CAVE_AIR or VOID_AIR. See the list here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
