### ISSUE TITLE
I would like to request a refund. 

### ISSUE THREAD

**Issue by shanndn** [kangarko/Winter#18]
Hello! I recently just purchased this plugin. It was very nice but it caused my server insane amounts of lag and TPS issues. I tried to adjust the settings as much as I could. I even tried to add melting and it made it way worse. The more players that joined my server it just got worse. This plugin seems to be not suited for the amount of people on my Minecraft survival server. I would like to refund the plugin please.

**Comment by kangarko** [comment]
Email me from the paypal address of your purchase to support at mineacademy.org
