### ISSUE TITLE
Snow on trapdoors

### ISSUE THREAD

**Issue by mormoon** [kangarko/Winter#18]
Hi,

In version 1.1.3 snow appears to be forming on trapdoors, even if being listed on the ignore list.

    Do_Not_Place_On:
    - ICE
    - BARRIER
    - FENCE
    - STEP
    - SLAB
    - AIR
    - TORCH
    - LONG_GRASS
    - DOUBLE_PLANT
    - YELLOW_FLOWER
    - SUGAR_CANE
    - BUTTON
    - WATER
    - CARPET
    - WHEAT
    - STAIRS
    - SIGN
    - BANNER
    - CHEST
    - DAYLIGHT_DETECTOR
    - SHULKER_BOX
    - IRON_BARS
    - WEB
    - FARMLAND
    - COBBLESTONE_WALL
    - TRAPDOOR
    - ARMOR_STAND

**Comment by kangarko** [comment]
Please test the upcoming release 1.1.6.
