### ISSUE TITLE
Problems/Suggestions

### ISSUE THREAD

**Issue by CrashOverrideMC** [kangarko/Winter#2]
Just got this Plugin and just like all your other great work.

I did notice some bug:
1) If you disable snow terrain, then Snowman die right as they spawn.
2) at first i turned on the snow terrain, but notice snow was above air blocks, i know air is a block in itself.. and could be add to block list of do not spawn on, but just seems weird it would do that..

suggestions:
Wish we could have a way to disable just individual features in certains worlds, like in my lobby i want snow, but my other worlds i want Snowman and Gifts, but can't do one without the other currently

**Comment by kangarko** [comment]
Hey!

1. Cannot reproduce. My snowman lives if Snowman.Disable_Melt_Damage is on true.
2. Yes, that's weird but I have added it to Terrain.Snow_Generation.Do_Not_Place_On. (just add AIR there)

Thanks for the suggestion! This unfortunately requires major rewrite which for, I in the times of exams, don't have time for. Thank you for your understanding.
