### ISSUE TITLE
1.16.4: Commands / Setup?

### ISSUE THREAD

**Issue by swim709** [kangarko/Winter#2]
Just purchased the plugin, really excited to use it. Just wondering, before I actually add in the .jar file to my server, are there any resources for useful commands or setup guides? I noticed the Wiki was empty.

Mostly just wondering what will happen by default when I first start up the server? I'd like to add the plugin now to check things out, but I don't want it to actually start snowing until December 1st. Should I run the server with the plugin, then stop and disable it quickly so I can examine the config files? Or will it not actually start snowing until I enter a command?

**Comment by kangarko** [comment]
Hi! 

Nope, Winter has everything you need packed within its settings.yml. It also contains comments to explain how each feature works.

I recommend you put it on a test server first. There's some options enabled you may want to disable first, such as snow generation, and then simply copy Winter/ folder with settings.yml into your production server.

Snow generation is fully automatic. Snow particles are also automatic but each player can disable them via a command, I think /winter snow

Matej
