### ISSUE TITLE
Chest date issue?

### ISSUE THREAD

**Issue by frizzbee30** [kangarko/Winter#20]
Hi, getting an error, that I suspect is the date range as we near the end of 2017. 

I have created a large number of prize chests hidden around a large world, many have dated periods that extend into January. (no idea where they are placed as there were no errors upon dating them to investigate further)

If this is the issue, could you please add a default so that if the end date is lower than the start, it defaults to the next year? I'm hoping these will work, as trying to find and correct them would be a problem, unless I can edit the db successfully

I did try opening the db, but had no luck ?pass-worded

https://pastebin.com/NNiMgvqE

Thanks

**Comment by frizzbee30** [comment]
Just to confirm, the plugin won't accept forward dated chests, i.e. Jan onward.

**Comment by kangarko** [comment]
Good notice. Will fix asap.

**Comment by frizzbee30** [comment]
Brilliant, thanks  :)
