### ISSUE TITLE
Ability for staff to modify/delete chests

### ISSUE THREAD

**Issue by mormoon** [kangarko/Winter#21]
Currently only the original owner/creator of a gift chest can make changes to it.  Can you make an enhancement of who'm created the chest and give staff permissions to modify the contents and destroy the chest?

**Comment by mormoon** [comment]
Also, the receiver of the chest cannot destroy the chest.

**Comment by kangarko** [comment]
Currently if a player is operator they can bypass the chest protection. Permissions will be coming shortly.

**Comment by kangarko** [comment]
Added. Closing.
