### ISSUE TITLE
Snow doesn't melt below structures

### ISSUE THREAD

**Issue by mormoon** [kangarko/Winter#22]
The structure was build during the "winter season". The winter season is now over, but under structures snow doesnt melt.

![2018-01-05_16 10 26](https://user-images.githubusercontent.com/7835585/34614863-2d16b656-f233-11e7-9cec-bb064cdb4ba6.png)

**Comment by kangarko** [comment]
Hello,

Winter uses exactly the same algorithm for snowfall as for melting, just in reverse. Thus I suppose the snow was not added by Winter, but by other measurements and Winter cannot locate it as we only remove snow from the top blocks.

**Comment by mormoon** [comment]
I'm fairly certain that the snow is from winter, because this is a restricted island, and only staff can build on it. I think this has something to do with spigot because when using worldedit (//thaw) the snow isn't being removed either. I must select the area and replace snow_layer with air to clean up huge area's. This winter plugin is great, but mysellf and staff where quite busy in cleaning up the "mess" (snow and ice) created by winter.

**Comment by kangarko** [comment]
Just been reviewing the code, and this is how it's done:

![a](https://i.imgur.com/bVOBzvi.png)

We search for the first free non-snowy block from the sky, from level 256 we subtract by 1 until we reach it. The same is applied for both melting and snowing, so I am very confident in that Winter did not place the snow (or it placed it when the structure above it did not exist and so the terrain was the highest block at that location). I am sorry, I don't plan to rewriting the plugin right now and adding a second check from bottom to top would cost -50% performance loss.
