### ISSUE TITLE
Minecraft 1.16.4: Snowmans

### ISSUE THREAD

**Issue by Ewwe** [kangarko/Winter#22]
Hi, is there any possibility to reduce or disable snowman spawning ? They are overspawned and they cause severe tps drops

**Comment by kangarko** [comment]
Hmm not right now but we'll add this as a suggestion, thank you!

**Comment by Ewwe** [comment]
Ok np :) For now i deny spawn for snow_golems in worldguard ( im writing this as hint for others )
