### ISSUE TITLE
help menu keeps getting larger every time I use it...

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/Winter#25]
https://imgur.com/a/Ef5IE

This effect is being applied to EVERYONE who uses the help menu.  i don't know if this is a side effect of /wt reload or not.  Also I can't find information on permissions for this anywhere?  I just tried the /wt snow command from a regular user and used the error to apply the permission for "snow from own perspective" but can't locate more important permissions for everyone to have like for gift boxes and things... the link to the wiki takes me to this github... which has no wiki.  Thanks!

**Comment by kangarko** [comment]
Duplication will be fixed. I am sorry for forgetting about the Wiki, I have wrote a quick go-to there. Ask me below if any questions.

**Comment by mrcoffee1026** [comment]
Does this plugin alter snowball behavior COMPLETELY?  We used to be able to use them in PVP regions and now... they do nothing, i'm thinking this plugin altered them or maybe a more recent build removed the feature - AGAIN, but I'm really hoping not.  In any case if I'm to keep this on for the gift box thing I need a way to give snowballs back their knockback ability.

**Comment by mrcoffee1026** [comment]
sorry I sorted the snowball thing out.. forgot i had this old mechanics plug that re-enabled snowballs but had to remove it since it did weird things to armor.  Thanks again.

**Comment by kangarko** [comment]
No problem, sorry for the late reply. Winter does affect snowballs because we make them cause real damage, but that's only for when the shooter is a Snowman.
