### ISSUE TITLE
1.16.4: Snow particles not appearing

### ISSUE THREAD

**Issue by advaleigh** [kangarko/Winter#25]
Paper 336, Winter 2.5.2, vanilla client, snow particles are not appearing in-game despite "weather disable" false and "snow enabled" true. This same settings file worked properly last year with earlier versions. Client is configured to show particles (eg rain works). Snow is generating correctly on the ground. No errors/warnings in the server log.

We run this plugin all winter (4 months) to make a winter season, and enjoy it very much.

**Comment by kangarko** [comment]
I am so sorry, I cannot reproduce on 1.16.4. ZIP me your folder.

<img width="1111" alt="Screenshot 2020-12-22 at 19 23 42" src="https://user-images.githubusercontent.com/1918426/102920558-3b3e1780-448b-11eb-8b66-307712988fde.png">

**Comment by kangarko** [comment]
Please update to the next version and reset your settings just for safety and use the next upcoming release.

**Comment by advaleigh** [comment]
Will do. Did you find a problem?

**Comment by kangarko** [comment]
No, works just fine for me. Next version coming up today.

**Comment by advaleigh** [comment]
Oh. Well I still have this issue. What folder did you want me to zip up? Just the plugin folder, or the whole server (presumably without the world files)?

**Comment by kangarko** [comment]
Wait for the next version, if still doesnt work try resetting your whole winter/ folder. Let me know below if that will help.

**Comment by advaleigh** [comment]
ok
