### ISSUE TITLE
1.16.4 (PaperMC): Snow generation leads to corrupted chunks

### ISSUE THREAD

**Issue by ThisIsTenou** [kangarko/Winter#26]
I've been experiencing corrupted chunks when snow generation is enabled. This has led to major issues and huge downtimes.

After a random time, usually one to two days with snow generation being enabled, you'd see messages like this:
`Saving oversized chunk [-14, -15] (1720638 bytes} to external file ./world/region/c.-14.-15.mcc`.
That's a corrupted chunk. As soon as someone gets near the affected chunks, the server will stop responding to _anything_.

Here's a full log, from start to death:
[server.log](https://github.com/kangarko/Winter/files/5725826/log.txt)

Please let me know if I can be of any further assistance to get this resolved.

**Comment by bobhenl** [comment]
Is it happening even when you disable snow layers?

**Comment by kangarko** [comment]
Hey!

So sorry to hear this! Can you please ZIP me your folder? Bob had a great suggestion, please let me know if this happens when snow layers are disabled.

Matej

**Comment by ThisIsTenou** [comment]
Hey @kangarko, I can't say whether it happens as well when layering is disabled. I (for obvious reasons) didn't want to try it on our production system and don't have the capacity to dedicate a testing system to it, currently.

I might be able to test things out after the holiday season.
[Winter.zip](https://github.com/kangarko/Winter/files/5732733/Winter.zip)

**Comment by kangarko** [comment]
Okay so you had snow generation disabled — did it happen with the exact settings you've shown to me?

If so, disable Psycho by setting this to false immediately. Psycho uses NMS so anything other than Spigot or Paper can lead to this, also NMS is obfuscated and can lead to this. Very certain this comes from Psycho feature. Snow generation is fine, we had thousands of people use Winter for many years without any issues. 

```
# Watch for entities spawned naturally, and convert them into a passive Snowman instead.
  Transform:

    # Convert spawned monsters to Snowman occasionally?
    Enabled: true
```

**Comment by kangarko** [comment]
Noticed you were indeed on Paper. Perhaps any other world or tag or nms plugin is interfering with psycho causing this. You can also report this to Paper for their investigation.

**Comment by ThisIsTenou** [comment]
Hey there, sorry for not clarifying. This is the configuration we're currently using. The issues were present when Snow Generation was enabled:

```
# Covering your world with snow. Multiple layers are supported!
  Snow_Generation:

    # Randomly place snow onto blocks around the player.
    # * YOU NEED TO HAVE THIS ENABLED if you want to MELT your snow *
    Enabled: true
```
This was only disabled in the zip I provided, as I forgot to revert this setting bevor sending it. Everything else remained untouched and, since we've disabled said setting, there have been no further issues.

Also, afaik we don't have psycho enabled. Only that some mobs will be replaced with friendly snowmen.

Regarding your suspicion that there could be interfering plugins, here's the full list of installed Plugins:
```
BetterChair
BlockyLog-2.3.0
ChristmasPlus-2.16.0
CoreProtect-19.3
Dynmap-3.1-beta5-spigot
LPC-3.1.1
LWCTrust-1.0.3
LWCX-2.2.6
LuckPerms-Bukkit-5.2.35
MobFarmManager1.5.9.0
PlaceholderAPI-2.10.9
ProtocolLib
SetHomes-1.2.7
SignShop-3.5.0
TabList-v5.5.0
Vault
Winter-2.5.2
sleep-most.4.6.3
worldedit-bukkit-7.2.0-dist
worldguard-bukkit-7.0.4
```

**Comment by kangarko** [comment]
CoreProtect can cause this because it's manipulating chunk data. Personally I had some issues related to this in 2014 then we switched to Prism. Can't be 100% certain, but it looks like Winter is not causing this per say.
