### ISSUE TITLE
Feature Request: replace regular snowfall option

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/Winter#26]
'As in display 'instead of" instead of "in addition to" the vanilla minecraft snowfall.  I would like to apply this to the world year round, having it only effecting snow biomes.

**Comment by kangarko** [comment]
Hey,

I am sorry this is not possible like that. You can set Weather.Disable to true to turn off weather completely, and just have the particle-based snow toggled on instead.

**Comment by mrcoffee1026** [comment]
awe... so sad :/  Thank you anyway!
