### ISSUE TITLE
Snow Golems Causing High Tick Rate

### ISSUE THREAD

**Issue by RedZephon** [kangarko/Winter#27]
Here's my latest timings report, it seems that Snow Golems are causing a lot of issues on my server. I tried lowering the spawning rate and doing a kill-all but they still seem to be problematic.

https://timings.aikar.co/?id=d319b5556623483c87528ddad2e937c5

**Comment by bobhenl** [comment]
Is it happening when you try to "deop" them a little bit, for ex. disabling them protection against zombies etc.?

**Comment by RedZephon** [comment]
So I had buffed them to spawn a bit more often and it was fine for a few days, then they randomly started spawning uncontrollably, like 5000 in 30 seconds. So I tried lowering the %, didn't help, then turned off spawning.

I had also nerfed their damage as well.

**Comment by kangarko** [comment]
Thanks, we'll try to fix it but snow golems use NMS methods that are unsupported and obfuscated, can't guarantee anything at this point.
