### ISSUE TITLE
Snow particles but no snow on the ground.

### ISSUE THREAD

**Issue by setoncarmichael** [kangarko/Winter#27]
Extremely new to this, in fact just purchased it, I'm seeing all the snow particles but nothing is actually accumulating anywhere. 

Spigot 1.13
Plugins List: TablistPing, dynmap, AntiRespawnScreen, PluginContructorAPI, PixelPrinter, PEX, Craft Display, Winter, TreeGravity, JoinMessage, Vault, MV Core, ProtocolLib, Essentials Core, Essentials Chat, Essentials Spawn

**Comment by kangarko** [comment]
Solved.
