### ISSUE TITLE
Dated chest issue

### ISSUE THREAD

**Issue by glorying16** [kangarko/Winter#29]
Having trouble with the latest update on 1.13.1 and dated chests. There are no errors, but it will not allow people other than the owner to open the chest. It only says "This chest is only accessible on 16.10". (Which is also the server date).

**Comment by kangarko** [comment]
May I see your text on the chest sign?

**Comment by glorying16** [comment]
https://i.imgur.com/cDDlpJN.png

**Comment by Magnum97** [comment]
I am having a similar issue but only on a date range. With a single date it works. This is what I put on my signs:
Single date example:
`[Dated]
24.11`
That worked for Nov 24th. My ranged date example:
`[Dated]
24.11-24.12`
It tells users it can only be opened between 24-11 and 24-12.  I am using v 1.4.2 on a 1.12.2 final version spigot server. I have the same issue on paper version: git-Paper-1589.

**Comment by kangarko** [comment]
Fixed
