### ISSUE TITLE
Sorry but I would like a refund

### ISSUE THREAD

**Issue by daansgs** [kangarko/Winter#3]
Hi, I really like what you do but me and our developers keep running into a tonne of issues: 
- It's still raining while snowing even when disabled
- The console keeps posting hundreds (spamming) of error messages every time I try to run a command
- The server crashes when executing some commands
- The snow-particle count doesn't work/ doesn't wanna in- or decrease
- It sometimes snows in the hub world even when that world isn't in the config

As I mentioned I really like the idea and aspects but it just is not the right plugin for us. 
I would love to hear from you and wish you a great day!

**Comment by kangarko** [comment]
Hey!

I am going to refund you no problem, however what you mentioned is pretty concerning so I am wanting to fix this for everyone else using Winter. Can you please post me:

1. The console errors
2. What exact commands crash the server?

Regarding snowing, there is a difference between Winter's particle snowing and vanilla snow. We can't disable vanilla snow unless you completely turn off the weather. If you see snow, it's probably the vanilla one not particles. Please correct me if I am wrong. Same goes for raining.

At the end, just let me know your paypal address and I'll refund you the money and as an apology you can keep the plugin, all I ask is to post these bugs so that we can get them solved asap!

**Comment by daansgs** [comment]
Hi, thanks for getting back to me so quickly.

If there's a way to get everything fixed then I'm more than willing to let
you keep the money since I do admire what you do and the ideas + mods that
you have.

I get an error like the screenshot I sent with this mail when using the
populate command. This is the exact error:

 at
org.bukkit.craftbukkit.v1_16_R2.CraftServer.tabCompleteCommand(CraftServer.java:1883)
~[patched_1.16.3.jar:git-Paper-204]
        at
org.bukkit.craftbukkit.v1_16_R2.CraftServer.tabComplete(CraftServer.java:1855)
~[patched_1.16.3.jar:git-Paper-204]
        at
org.bukkit.craftbukkit.v1_16_R2.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:58)
~[patched_1.16.3.jar:git-Paper-204]
        at
com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71)
~[patched_1.16.3.jar:git-Paper-204]
        at
com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:596)
~[patched_1.16.3.jar:git-Paper-204]
        at
com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:579)
~[patched_1.16.3.jar:git-Paper-204]
        at
net.minecraft.server.v1_16_R2.PlayerConnection.lambda$a$4(PlayerConnection.java:584)
~[patched_1.16.3.jar:git-Paper-204]
        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18)
~[patched_1.16.3.jar:git-Paper-204]
        at
net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
~[patched_1.16.3.jar:git-Paper-204]
        at
net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
~[patched_1.16.3.jar:git-Paper-204]
        at
net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
~[patched_1.16.3.jar:git-Paper-204]
        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135)
~[patched_1.16.3.jar:git-Paper-204]
        at
net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128)
~[patched_1.16.3.jar:git-Paper-204]
        at
net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
~[patched_1.16.3.jar:git-Paper-204]
        at
net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089)
~[patched_1.16.3.jar:git-Paper-204]
        at
net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003)
~[patched_1.16.3.jar:git-Paper-204]
        at
net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
~[patched_1.16.3.jar:git-Paper-204]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
Caused by: org.mineacademy.winter.lib.fo.exception.FoException: Report:
Found {plugin_name} variable calling hasPerm(CraftPlayer{name=DaanSGS},
{plugin_name}.command.populate).This is now disallowed, contact plugin
authors to put winter in their permission.
        at org.mineacademy.winter.lib.fo.Valid.checkBoolean(Valid.java:81)
~[?:?]
        at
org.mineacademy.winter.lib.fo.PlayerUtil.hasPerm(PlayerUtil.java:266) ~[?:?]
        at
org.mineacademy.winter.lib.winter.commands.PopulateCommand.tabComplete(PopulateCommand.java:145)
~[?:?]
        at
org.mineacademy.winter.lib.fo.command.SimpleCommand.tabComplete(SimpleCommand.java:1185)
~[?:?]
        at
org.mineacademy.winter.lib.fo.command.SimpleCommandGroup$MainCommand.tabComplete(SimpleCommandGroup.java:506)
~[?:?]
        at
org.mineacademy.winter.lib.fo.command.SimpleCommand.tabComplete(SimpleCommand.java:1185)
~[?:?]
        at
org.mineacademy.winter.lib.fo.command.SimpleCommand.tabComplete(SimpleCommand.java:1164)
~[?:?]
        at
org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:244)
~[patched_1.16.3.jar:git-Paper-204]
        ... 18 more

 It also sometimes snows in Minecraft and it was actually raining for a
while yesterday (until I manually stopped it). Also it keeps snowing in
worlds that I disabled (not added to config) but that doesn't give any
errors, right now it's working in the correct worlds but whenever I change
it there's about a 50/50 chance of it not listening to the config and doing
whatever it wants it seems like.

Again, I hope you can help me out because I don't actually want to screw
you by refunding since you put effort into it, you contacted me quickly and
I like your dedication.

Thanks in advance,

Daan S.

**Comment by kangarko** [comment]
Thank you I fixed that!
