### ISSUE TITLE
Hi, whats the command? The snow and the snowman start bringing lags to my server. Can I remove everything at once?

### ISSUE THREAD

**Issue by game1533** [kangarko/Winter#30]
Hi, whats the command? The snow and the snowman start bringing lags to my server. Can I remove everything at once?

_Originally posted by @game1533 in https://github.com/kangarko/Winter/issues/29#issuecomment-752137372_

**Comment by game1533** [comment]
Cause the built in snow remove commend (which scans all chunks for 2 hours) just increases the folder size and there is still too much snow.

**Comment by kangarko** [comment]
You can remove all snow in all chunks using the /winter snow command.

**Comment by game1533** [comment]
Thats just the command to make the particles visible
