### ISSUE TITLE
Auto-tab-complete hide command if player has no permission

### ISSUE THREAD

**Issue by x1p** [kangarko/Winter#31]
Description of issue or feature request:
Players who don't have access to specific commands are able to tab complete them in 1.13.x
Players see much commands they should not be able to see using /(tab). This should be possible.

Example:
`/w`(tab)
Exposes:
```
winter populate
winter reload
winter snow
```
Same for `/wt`

Can this be solved?

**Comment by kangarko** [comment]
Hey, actually with the current system it is not possible to hide it, but I hided the arguments of /winter populate

Thank you for your understanding.
