### ISSUE TITLE
All now should melt

### ISSUE THREAD

**Issue by swim709** [kangarko/Winter#31]
Snow doesn't melt if it is "covered". Example, snow covered a field, but we planted tree's. Now the snow does not melt from the base of the tree until we manually remove it.

1) How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)
Nobody would have to spend time manually digging snow from beneath tree's (or any other structure that was built after the snow arrived)

2) What would happen if we won't implement this feature? How's your server being affected?
Snow will remain in areas that it shouldn't, and I have to spend time removing it to restore the biome to it's proper appearance.

3) If suggesting something new - Can the old system be modified/improved instead?
I'm not sure.

**Comment by kangarko** [comment]
Thanks. However right now we're only fixing major bugs to Winter, it's open source, anyone can contribute with feature requests.

**Comment by swim709** [comment]
I would consider this a major bug, as it will prevent me from using this plugin again on my next map. I also couldn't recommend it to anyone with this bug still present.

**Comment by kangarko** [comment]
I understand. And I don't want to seem arrogant, I simply don't have time for this. Winter is now open source, anyone can contribute.
