### ISSUE TITLE
Minecraft Version: Your Question Title

### ISSUE THREAD

**Issue by xBlockBuster98** [kangarko/Winter#32]
1) Please include your Minecraft version in your title:
    I was testing the plugin in 1.8.8

2) Try to keep it simple and clear, providing us all information necessary to answer your question. You can use imgur.com to 
   https://imgur.com/4ItDOWe I can't understand the errors

when the server loads the plugin Winter, it showsme this error: https://imgur.com/4ItDOWe, why? Same with Boss

**Comment by kangarko** [comment]
Use Java 11 from Oracle
