### ISSUE TITLE
Dated Chest  double loot

### ISSUE THREAD

**Issue by Blueeyestar** [kangarko/Winter#33]
Hi, we have an issue on our Server with your Plugin Winter. When I'am creating a Dated Gift Chest with a doublechest and a sign on it (1.Line [Dated] 2.Line 25.11.-30.11.) all other users are able to loot the chest in the preview view and again in the normal looting view. so the result ist a double loot. It seems to be a bug in your plugin. Could you pls fix it. I need this. Thanks a lot.

**Comment by kangarko** [comment]
Fixed, thanks
