### ISSUE TITLE
Snow troubles - damaged world?

### ISSUE THREAD

**Issue by Aeyesx** [kangarko/Winter#34]
Hi!

A year ago,
I bought this plugins to make things Sn0wWy.
It promised not to damage the world so I toke it...
Well ... since then this is what the world looks like http://aeyesi.eu:8123
You can see many areas where snow was permanently removed after melting process and well there was no easy fix for that...

Either way...
If I buy this again, will it work better? Was this addresed? ^^
Thanks

**Comment by kangarko** [comment]
Hey,

are you suggesting that we only melt snow that Winter has created and do not touch the other one?

**Comment by Aeyesx** [comment]
Well it removes naturally generated snow from entire world so... I guess it shouldn't do that? but then... yeah thats hard to do

**Comment by kangarko** [comment]
Ahoj, nieje možné sledovať aký sneh položil plugin z praktických dôvodov, databáza by obsahovala milión blokov a museli by sme rátať s tisíckami prípadov kedy sa odstráni (napr. zničí ho hráč, posunie piest) takže reálne by to aj tak nebolo stabilné.

Nateraz môžeš použiť /winter populate príkaz na pridanie alebo odobranie sneho z celej mapy. Skús ho použiť len prvý raz, nič neurobí, prečítaj konzolu a napíš mi odhadovaný čas pre tvoju mapu.

**Comment by kangarko** [comment]
Myslím že to sa dá, ďakujem za ideu.

**Comment by Aeyesx** [comment]
Kdyby se podařilo,
Byl bych vděčný za možnost vrátit sníh do biomů kde se vyskytuje přirozeně. 
Díky ^^

**Comment by GermanMinersNET** [comment]
Hello, there,
even if I don't speak czech, I think I could understand the content quite well via google translator.
The idea is to skip snow biomes when the snow is melted by the plugin. This should be done by checking whether the snow block is in a snow biome or not. Did I understand that correctly? 

Will this feature be added or not? In this case I would wait to use Winter until it is added.

**Comment by kangarko** [comment]
This feature was added into the next Winter update scheduled for either today or tomorrow ;)

For non-Slovak/Czech speakers, we have discussed that Winter should only melt/remove snow from biomes where it does not appear naturally, and preserve snow in naturally snowy biomes.
