### ISSUE TITLE
Snow and frozen water is not melting

### ISSUE THREAD

**Issue by ArZorMC** [kangarko/Winter#35]
After attempting to have the snow and ice melt automatically and that was unsuccessful i saw mention of the command /winter populate
Then i saw the massive warning, and a notice it would kick all players and take 64 hours 4 minutes 54 seconds
That's a giant no go for me. I have a feeling i missed something in configuring things to melt properly.
My settings are as follows:
https://pastebin.com/tuq6XtDe

Winter Version: 1.4.6
Paper Version: git-Paper-464 (MC: 1.13.2)

**Comment by kangarko** [comment]
Responded in PM
