### ISSUE TITLE
Timed chests not working? 

### ISSUE THREAD

**Issue by sannielollie** [kangarko/Winter#36]
Hi there  :) 
Timed chests are not working on my server. What can be the cause of this? I dont get it :(
Screenshots are made earlyer when i reported the issue at spigotmc. 
https://i.imgur.com/tbCCGO1.png

https://i.imgur.com/iK1kJvl.jpg

Server date & time are both correct.. Help would be appreciated, thanks!
Running on latest spigot 1.12.2 build. 
Issue not fixed with the latest update, still the same issue. Year is set to 2018 in the main config.
Issue: Timed Chests can not be opened by other players. If you need any more info, i will be glad to help sorting out this issue, just let me know and i will do what i can.

**Comment by kangarko** [comment]
Hey, thank you for your report, I am on it and will get back to you soonest possible (1-2 days)

**Comment by kangarko** [comment]
@sannielollie still happens on the latest release?

**Comment by kangarko** [comment]
We have fixed the problem

**Comment by sannielollie** [comment]
I'll check if the problem still occours. Thanks!
