### ISSUE TITLE
Region option to enhance the plugin further

### ISSUE THREAD

**Issue by cobrex1** [kangarko/Winter#36]
I would like to suggest having a region option within the configuration settings as well as a world option. 

I am looking to set up a winter event and don't really want to create an entire world for it, but have a designated WorldGuard region.

I feel with would benefit everyone as many users will create regions for events, rather than whole worlds.

It will not affect my server moving forward, but feel that this is an enhancement.

**Comment by kangarko** [comment]
What would the region or world option control? You want to restrict snow particles or snow generation in certain regions or worlds?

**Comment by HenrikoMagnifico** [comment]
I agree with this request! I have a server with a hub world that would look great alongside the Winter plugin, but there are portions of it with flowing water that would potentially spill over if parts of it froze over, as well as potentially causing other problems. The solution was to disable Winter in the hub world, but if it supported WorldGuard regions that would be even better!

**Comment by kangarko** [comment]
Sorry for the delays, I added it!
