### ISSUE TITLE
Rain instead of snow

### ISSUE THREAD

**Issue by GermanMinersNET** [kangarko/Winter#37]
In version 1.8.8 of Spigot with the default config of Winter rain is not changed to snow. The particles work fine, but if the weather changes to rain, it actually rains (raindrops) and no snow falls.

This problem already existed last year and I thought I had already reported it, but found only a different report from me. I think last year I just switched off the rain completely.

**Comment by kangarko** [comment]
I am sorry but for snowy particles you must have Disguise_Biomes to true and that may or may not work on such old Minecraft versions.
