### ISSUE TITLE
[Feature Request] Expanding Beyond Just The Winter Season

### ISSUE THREAD

**Issue by HenrikoMagnifico** [kangarko/Winter#37]
I'm sure this isn't the first time this has been requested, but since I couldn't find any open requests for it here on GitHub I thought I'd at least write it out publicly! It would be absolutely outstanding if the Winter plugin could start introducing seasons beyond just Winter. There are plugins on the market that do feature other seasons, but none of them are nearly as feature packed or well designed as Winter is. Unique features in each season could include (just examples):

- Especially clear and sunny weather in the summer.
- The player getting too warm during summer if they're wearing a full set of armor.
- Crops growing quicker in the summer.
- Trees leaves becoming orange / falling off in the fall.
- Especially rainy weather in the fall and spring.
- Higher chance of thunder storms in the summer.
- Windy in the fall, with blowing leaves in the wind and loose dropped items blowing away in the wind unless they're covered from it.
- Real life seasonal cycle, i.e. the season changes based on what the current season is IRL spanning across a whole year, or a specified time period.
- More "cold" mobs in the winter and more "warm" mobs in the summer, for example strays, penguins and polar bears in the winter and husks in the summer.
- Sand becoming too hot to walk on in the summer. And deserts causing heat stroke if you don't drink enough water.
- Mushrooms grow extra quickly in the fall.
- Planted flowers can spread to nearby places in the spring.
- Obviously, biome colors will change based on what season it is.
- Dirt becomes mud in the fall, and goes back to dirt in the late spring.
- Seasonal fish from fishing, some types are more common during certain seasons.
- Longer / shorter days in the summer and winter.
- Potentially new unique weather patterns like blizzards, hurricanes etc.

And much more...

This would of course be a huge undertaking, but it would be pretty awesome if you managed to pull it off nonetheless!

**Comment by ElBananaa** [comment]
Hey,
While I believe some of your suggestions are great, I think the main issue with them is that they don't match the plugin's name...
The plugin is named "Winter", not "Seasons" ^^

**Comment by HenrikoMagnifico** [comment]
> Hey, While I believe some of your suggestions are great, I think the main issue with them is that they don't match the plugin's name... The plugin is named "Winter", not "Seasons" ^^

Of course, and I should have probably specified that this was more of a dreamy "what if" plugin request than a request for the Winter plugin specifcally. If such a drastic change were to be implemented, it would most likely have to rebrand the whole plugin to "Seasons" or something akin to that.

**Comment by kangarko** [comment]
Thanks! Right now my plate is full, and as Banana pointed out, we would need a separate plugin for this. People looking for seasons would not even find our plugin, we would need to change the name to "Seasons" :)
