### ISSUE TITLE
[Feature Request] Adding Skiing

### ISSUE THREAD

**Issue by HenrikoMagnifico** [kangarko/Winter#38]
This is a feature request I believe would fit perfectly with the theme of the plugin- namely skiing! Imagine if you could craft skiis by combining sticks and wooden planks together, and then it's off to the slalom slopes! [There is already a mod](https://www.curseforge.com/minecraft/mc-mods/skiing/) that does pretty much what I had in mind already, but it's Forge mod and is both client side and server side. This feature would benefit players during the winter season, or in frozen biomes, where there's plenty of snow and tall peaks (especially with the new 1.18 lofty peaks biome).

**Comment by kangarko** [comment]
Thank you very much! Wonderful suggestion, however at present we do not have the resources to implement mods beyond the basics Minecraft support.
