### ISSUE TITLE
Advent Calendar

### ISSUE THREAD

**Issue by x1p** [kangarko/Winter#4]
I use Winter quite a few years now as an Advent Calendar and players always run into some problems because of some illogical issues.
I'm only talking about the Dated Gift function.
- Players don't understand that they can't click on the sign. They need to be told to click on the chest only.
- Players don't understand that they need to open the chest twice. They need to be told.
- Players don't understand that they need to grab the item(s) themselves. (They are used to crates)
- Players sometimes forget to have an empty place in their inventory.
All this causes a lot of the same questions. Staff members need to explain this often, despite instructions, warnings, etc. This leads to complaints like "I didn't get anything" causing staff to believe this and compensate for the lost items (possible scams).

Therefor I would like to suggest the following:
- ability to click on the sign as well as opening the chest
- ability to push item to inventory upon first time
- ability to drop item on the ground when the inventory is full.

**Comment by kangarko** [comment]
Hi there!

I added an option to disable chest previews as well as the ability for signs to open chests!

There are instructions to loot the chest again after the first open: https://i.imgur.com/nJa2lZE.png as well as the ability for players to drop the loot on the floor: https://i.imgur.com/B7ewIdu.gif

Thanks!
