### ISSUE TITLE
Remove Snow after christmas

### ISSUE THREAD

**Issue by hermandelul** [kangarko/Winter#4]
Hello. 

i want to implement this in an big survivalserver. (ca 500 have played on it, and dosens still active)
ive setup the plugin in an testserver and it works good. but. after newyear i want to disable the plugin.
is it possible the snow placed on normal/warm biomes melt? like an plain or oak forest?

it isnt an option to go every location with //replacenear snow air.

thanks sofar, great plugin.

**Comment by kangarko** [comment]
Great suggestion, I have added a switch that reverts the entire snow generation process into snow melting process!

**Comment by hermandelul** [comment]
thanks, i think i can download the new version with the same purchage form the Spigot site?
(think there is an delay in the new version to show on the site)

**Comment by kangarko** [comment]
Yes. It will be ready tonight in a few hours.

**Comment by hermandelul** [comment]
thanks
