### ISSUE TITLE
new form factor of snow

### ISSUE THREAD

**Issue by yellow-pillow** [kangarko/Winter#40]
hi, is it possible to make the generation of snow around a person a square, not a circle? it would look much cooler and more realistic, otherwise it is very noticeable that the snow falls in chunks + you can make exactly the radius of the snow falling in blocks, and not in chunks

**Comment by kangarko** [comment]
Thanks, however that would overlap and the more players standing in a location the more snow would generate. Mitigating this would involve thousands of math checks for each location block, degrading performance.
