### ISSUE TITLE
Error message and no snow particles

### ISSUE THREAD

**Issue by GermanMinersNET** [kangarko/Winter#40]
(Please excuse the bad formatting.)

I'm getting the following error on spigot 1.8.8, after that, no snow effects are shown anymore:

13:29:41 Thread-167/INFO: Winter 0301m//03722m Winter 1.5.2 encountered a IllegalStateException! Please check your error.log and report this issue with the information in that file.m
13:29:41 Thread-167/INFO: java.lang.IllegalStateException: Asynchronous entity world add!
13:29:41 Thread-167/INFO: 	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
13:29:41 Thread-167/INFO: 	at net.minecraft.server.v1_8_R3.World.b(World.java:2633)
13:29:41 Thread-167/INFO: 	at net.minecraft.server.v1_8_R3.Chunk.addEntities(Chunk.java:820)
13:29:41 Thread-167/INFO: 	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:49)
13:29:41 Thread-167/INFO: Winter 0301m//03722m 03722m*-----------------------------------------------*m
13:29:41 Thread-167/INFO: Winter 0301m//03722m  0311mError showing snow particles!m
13:29:41 Thread-167/INFO: Winter 0301m//03722m  0311mStopping task for safety.m
13:29:41 Thread-167/INFO: Winter 0301m//03722m  0311mIllegalStateException: Asynchronous entity world add!m
13:29:41 Thread-167/INFO: Winter 0301m//03722m 03722m*-----------------------------------------------*m

**Comment by kangarko** [comment]
Will be fixed
