### ISSUE TITLE
1.17.1: RealisticSeasons compatibility

### ISSUE THREAD

**Issue by AlessioGr** [kangarko/Winter#43]
Hi there!

I love the idea and am thinking of getting the plugin. However, I'm currently using RealisticSeasons (https://www.spigotmc.org/resources/realisticseasons-1-16-3-1-17-1-seasons-in-your-minecraft-world-temperature-update.93275/) which is an amazing plugin as well. Is it possible to use Winter alongside RealisticSeasons, or for you to add compatibility?

Basically, I'd like the RealisticSeasons winter to be replaced by your particle effects.

Thank you!

**Comment by kangarko** [comment]
You can just disable their particles and enable ours, those plugins should be compatible if their same features are enabled only in either RealisticSeaons or Winter.
