### ISSUE TITLE
How to make it not snow in a certain place?

### ISSUE THREAD

**Issue by TinyBolts** [kangarko/Winter#43]
How to make it not snow in a certain place? Its snowing on my spawn plots and covering them in snow. Cant really see their borders.

**Comment by TinyBolts** [comment]
also the leaves of trees arent changing color

**Comment by TinyBolts** [comment]
help

**Comment by kangarko** [comment]
Answered in PM.

Also a solution could be disabling Winter in your plot world, see the Worlds option in settings.yml
