### ISSUE TITLE
Cauldron with powder snow

### ISSUE THREAD

**Issue by P5ina** [kangarko/Winter#44]
A cauldron in a snowy biome fills with powder snow when it is snowing. Since it snows in all biomes in this plugin, I believe that powder snow should fill the cauldron everywhere. Many players on my server asked to add this feature, so I will be grateful if you add it.

**Comment by kangarko** [comment]
Thanks, I'll consider it, but since this is a micro cosmetics feature, I am putting this on hold since my plate is full right now.
