### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Yukylyu** [kangarko/Winter#45]

**Comment by ElBananaa** [comment]
> Hi i have a problem with winter and 1.17.1 :(
> 
> Your Minecraft version 1.17 is unsupported by Winter FoException Report: Your Minecraft version 1.17 is unsupported by Winter at org.mineacademy.winter.lib.fo.Valid.checkBoolean(Valid.java:81) at org.mineacademy.winter.lib.fo.remain.Remain.(Remain.java:240) at org.mineacademy.winter.lib.fo.Common.stripColors(Common.java:665) at org.mineacademy.winter.lib.fo.Common.log(Common.java:1211) at org.mineacademy.winter.lib.fo.Common.log(Common.java:1186) at org.mineacademy.winter.lib.fo.Common.logFramed(Common.java:1259) at org.mineacademy.winter.lib.fo.Common.logFramed(Common.java:1246) at org.mineacademy.winter.lib.fo.plugin.SimplePlugin.checkServerVersions0(SimplePlugin.java:552) at org.mineacademy.winter.lib.fo.plugin.SimplePlugin.onEnable(SimplePlugin.java:228) at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:511) at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:425)

Hey, 
Please make sure to use the latest version available on mcmarket: https://www.mc-market.org/resources/21645/
