### ISSUE TITLE
Minecraft Version: Issue Title

### ISSUE THREAD

**Issue by aries404** [kangarko/Winter#46]

**Comment by aries404** [comment]
Sorry forogt xD ok so basically when i try to apply snow to my world via winter it does thi
![2021-11-25_00 13 26](https://user-images.githubusercontent.com/65984098/143677447-7ac592d3-76dd-4c8a-8da9-11ff444255a7.png)
s

**Comment by aries404** [comment]
i am currently using the latest version of this plugin

**Comment by kangarko** [comment]
You need to add the blocks you do not want the snow to appear on to the Do_Not_Place_On key (use CTRL+F) in your settings.yml. I have a look at adding more default values there.

**Comment by ElBananaa** [comment]
Hey,
Here's an updated config file with the new 1.17.1 list: https://paste.gg/p/anonymous/9639bc55a4f34a6ba49b25a8d6f09d91
