### ISSUE TITLE
Weather stuck bug

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/Winter#48]
Attempting to utilize only the gift chest aspect of this plugin I disabled all the the other items like snow, ice melt, ice forming, etc... the result was glitchy weather.  Eventually it would rain in the world... and never stop, ever.  Server would ignore all commands having to do with weather.  A player could warp to a world where it was not raining and then go back to the world and there it would ALSO not be raining... forever.  Even after it started to rain naturally.  So they'd see dark clouds and hear thunder, but see no rain so there'd seem to be no reason for it.  If they had access to the essentials command... and not all players do... they could /pweather reset... at which point they would realize it was raining in the world (and had never not been raining in the world).  Disabling winter resolved this problem.  I don't know if this issue is limited to MC 1.12.2 or not that's the only place I've attempted it so far.  But my intention would be to put the plugin on and LEAVE it on... enabling features as I wanted them... but I can't do that if it breaks weather.

**Comment by kangarko** [comment]
Hey,

as per the code, we modify the weather when one or the second setting option is met, make sure you have them both on false:

![a](https://i.imgur.com/kUmbs78.png)

That's pretty much everything we're doing to the weather, it should reset itself to the vanilla state after you restart your server

![b](https://i.imgur.com/o2i3Wcd.png)

I added a minor tweak to stop the storm snow particles after reloading the config but I believe this is unrelated.

**Comment by mrcoffee1026** [comment]
snow storm was set to true while disable was set to false... so I guess i need snow storm to false also unless I intend to have weather stuck for people.  Thanks for the help on that... but even if it is set to "true" I don't think all weather cycling on the server should permanently stop.

**Comment by kangarko** [comment]
Closing, I hope that clarified things up. Thundering time is defined by Bukkit, that is given a random time period.
