### ISSUE TITLE
Error dont load in 1.13

### ISSUE THREAD

**Issue by RemcoPl** [kangarko/Winter#49]
Server version 1.13
Plugins version newst version (2.0.1)
27.04 17:03:38 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
27.04 17:03:38 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339)
27.04 17:03:38 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
27.04 17:03:38 [Server] INFO at org.mineacademy.winter.null. .cOm4.onEnable(SourceFile:226)
27.04 17:03:38 [Server] INFO at org.mineacademy.winter.null. .m.const(SourceFile:63)
27.04 17:03:38 [Server] INFO at org.mineacademy.winter.null. .o.native(SourceFile:24)
27.04 17:03:38 [Server] INFO at org.mineacademy.winter.null. .m.native(SourceFile:166)
27.04 17:03:38 [Server] INFO at org.mineacademy.winter.null. .l.native(SourceFile:129)
27.04 17:03:38 [Server] INFO at org.mineacademy.winter.null. .m$1.const(SourceFile:37)
27.04 17:03:38 [Server] INFO at org.mineacademy.winter.null. .m.strictfp(SourceFile:102)
27.04 17:03:38 [Server] INFO at org.mineacademy.winter.null. .m.const(SourceFile:135)
27.04 17:03:38 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498)
27.04 17:03:38 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
27.04 17:03:38 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
27.04 17:03:38 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
27.04 17:03:38 [Server] INFO at org.mineacademy.winter.null. .aQ$throw.init(SourceFile:117)
27.04 17:03:38 [Server] INFO at org.mineacademy.winter.null. .aQ.finally(SourceFile:26)
27.04 17:03:38 [Server] INFO at org.mineacademy.winter.null. .m.do(SourceFile:226)
27.04 17:03:38 [Server] INFO at org.mineacademy.winter.null. .l.else(SourceFile:252)
27.04 17:03:38 [Server] INFO at org.mineacademy.winter.null. .LPT6.const(SourceFile:83)
27.04 17:03:38 [Server] INFO java.lang.ExceptionInInitializerError
27.04 17:03:38 [Server] INFO Disabling Winter v2.0.1
27.04 17:03:38 [Server] INFO *-----------------------------------------------*
27.04 17:03:38 [Server] INFO Plugin is now disabled.
27.04 17:03:38 [Server] INFO Problem: java.lang.ExceptionInInitializerError
27.04 17:03:38 [Server] INFO Problematic section: Terrain
27.04 17:03:38 [Server] INFO Error loading configuration in settings.yml!
27.04 17:03:38 [Server] INFO *-----------------------------------------------*
27.04 17:03:38 [Server] INFO Loading configuration...
27.04 17:03:38 [Server] INFO |_|_| | | \|  |  |___ |  \ 
27.04 17:03:38 [Server] INFO | | | | |\ |  |  |___ |__/ 
27.04 17:03:38 [Server] INFO _ _ _ _ _  _ ___ ____ ____ 
27.04 17:03:37 [Server] INFO Enabling Winter v2.0.1

**Comment by kangarko** [comment]
Make sure you have 1.13.2.

Please post me your full startup log to pastebin.com

**Comment by RemcoPl** [comment]
I have updated the server tot the newst version of 1.13.2 and it fixed the problem
