### ISSUE TITLE
Bug with tallgras

### ISSUE THREAD

**Issue by hermandelul** [kangarko/Winter#5]
Hi,
there is an bug with tallgras
on a place where is an talgrass. the snow next to it is placed in the air.

![2017-11-23_19 29 12](https://user-images.githubusercontent.com/8301044/33185682-a4a087d6-d084-11e7-9172-e84c6bcf72e0.png)

![2017-11-23_19 26 47](https://user-images.githubusercontent.com/8301044/33185649-6dcd739a-d084-11e7-946e-d66583b53656.png)

**Comment by hermandelul** [comment]
another bug, Snow spawns on RED_FLOWER and WHEAT, even if i disable it in the config
`
Do_Not_Place_On: [ICE, BARRIER, FENCE, NETHER_FENCE, STEP, DOUBLE_STEP, DOUBLE_STONE_SLAB2, AIR, TORCH, LONG_GRASS, DOUBLE_PLANT, YELLOW_FLOWER, SUGAR_CANE, STONE_BUTTON, WOOD_BUTTON, FENCE_GATE, SPRUCE_FENCE_GATE, BIRCH_FENCE_GATE, JUNGLE_FENCE_GATE, DARK_OAK_FENCE_GATE, ACACIA_FENCE_GATE, SPRUCE_FENCE, BIRCH_FENCE, JUNGLE_FENCE, DARK_OAK_FENCE, ACACIA_FENCE, WATER, CARPET, STATIONARY_WATER, WHEAT]
`

**Comment by kangarko** [comment]
Hey, this will also be fixed in the next version.

**Comment by hermandelul** [comment]
@kangarko ok thanks. 

if you want you can join mine survuvalserver there is an lot of buildings, so you can test :-)

**Comment by kangarko** [comment]
Oh no thanks I have enough stuff to do for today :)
