### ISSUE TITLE
1.8: TPS issues with mid-playercount

### ISSUE THREAD

**Issue by AllenPlays** [kangarko/Winter#5]
Hey there, I purchased Winter a few days ago and have been noticing a ton of TPS issues since I brought the plugin into the server. Even with around 20-30 players online our TPS gets hit for around 5-10%, and seems to only be going up as more players login. I have the settings at nearly the lowest they could possibly go, so I'm not sure why we are still seeing such an impact on performance. I plan on turning up the settings as christmas gets closer, and if lag is happening with the current settings, I'm not sure if that will even be a possibility.

Config: https://paste.helpch.at/fabujokamo.php
Timings: https://timings.aikar.co/?id=b5da42eec74c457ca5a0057f7b82c598#plugins

**Comment by kangarko** [comment]
Your Terrain.Snow_Generation.Radius is too high. Decrease it from 10 to 4 or even 2 and the lag from generating and finding snow locations should decrease, too.
