### ISSUE TITLE
Latest update breaks plugin 1.12.2 Paper

### ISSUE THREAD

**Issue by SladeHazard** [kangarko/Winter#50]
I have tried using default configs.
the latest update for winter in 1.12.2 server version makes it so the snow only spawns at 1 random part of each world.
![image](https://user-images.githubusercontent.com/45261094/143785641-aa14784e-bd50-4a1c-9d1e-eae8c9fd76c9.png)

there Is no snow at any other place both with realistic disabled & enabled.

**Comment by kangarko** [comment]
Set Require_Snow_Biomes to false in settings.yml, otherwise I am unable to reproduce your issue.

**Comment by SladeHazard** [comment]
require biome etc are already false.

this bug is only happening in my current worlds. but I regenerate a new world 'world' it does not happen and the plugin starts working fine? did you change anything related to chunks in the new update?

**Comment by kangarko** [comment]
Nope. Must be another plugin then or some weird issue with your server/particles etc. Really strange, since 2017 you are the only one reporting this. I tested on a 1.12 server.

**Comment by SladeHazard** [comment]
I've already tried with only winter plugin on the server.
with both realistic snow and biome req set to false.

The issue is only happening in few areas of my world. and if I generate a
new vanilla world the plugin works fine there. no region restrictions are
set either. however if I load the 3.0.2 version, everything starts to work
fine.

**Comment by kangarko** [comment]
Send me your plugins list by typing /plugins in the console and copying the output. If you use WorldGuard try removing it for a short test to see if it helps. If so, then you need to check if you have Regions flags set to false under Snow and Terrain Generation settings.yml sections.

**Comment by SladeHazard** [comment]
bro I literally just mentioned I've tested with 0 plugins. I can send you
my server folder with just world..

**Comment by kangarko** [comment]
Sorry, I missed that. Yes you can do that, would be great so I can test it.

**Comment by SladeHazard** [comment]
https://workupload.com/file/rmZkDVubXGH

**Comment by SladeHazard** [comment]
btw chaos factor does nothing either.
and since you added psycho mode for 1.8 why not add it for 1.12 too..
unless you meant 1.18

**Comment by kangarko** [comment]
Got Psycho working on 1.12 and fixed your bug! (So sorry for the delay!)

![a](https://i.imgur.com/ogdKM9U.png)

Next version will be out today or tomorrow.

**Comment by SladeHazard** [comment]
The bug was never fixed, you were standing in a different chunk and you were in air.
Please go to 11 67 -23

if you fly up the snow is there but not on the ground

**Comment by kangarko** [comment]
Sorry for the delay, I cannot reproduce with this build:
[Winter-3.0.6.jar.zip](https://github.com/kangarko/Winter/files/7761093/Winter-3.0.6.jar.zip)

![2021-12-22_09 18 17](https://user-images.githubusercontent.com/1918426/147059494-dd1f357b-2ab9-48e8-9527-8740f1bb8a08.png)

**Comment by kangarko** [comment]
You have lightning issues in some chunks, which may render particles invisible. You need to fix those issues first, as you mentioned, if particles are shown properly in other worlds then it's your world's issues with lightning/chunks.
