### ISSUE TITLE
1.17.1 Gift Preview

### ISSUE THREAD

**Issue by x1p** [kangarko/Winter#52]
Paper 1.17.1
Winter 3.02

Dated gift chests can be looted twice when Preview is false.

I've setup a advent calender with dated chests. Normally I have preview enabled, but I decided to skip the preview this year.
Now it's able to loot them twice!
So I disabled it again.
This feature was added last year during the advent time, so I couldn't use it.
This year it's bugged, so I can't still use it cuz I don't want to change the rules during the event to confuse players.
On to next year....

**Comment by kangarko** [comment]
Thanks, fixed! I will push the release in 1-2 days, because I need to finish 1.18 compatibility first.
