### ISSUE TITLE
1.12.2: Plugin broken after latest updates

### ISSUE THREAD

**Issue by SladeHazard** [kangarko/Winter#54]
The snow appears if I create a new world. But in my old worlds it's only appearing in some places.
If I add old version it starts working fine again.

realistic snow is set to false.
requires snow biome is set to false.

**Comment by SladeHazard** [comment]
Please review your code , bug was introduced in version 3.0.2.

**Comment by kangarko** [comment]
Duplicate of https://github.com/kangarko/Winter/issues/50
