### ISSUE TITLE
Suggestion: Add "/winter edit" or something to allow admin to edit the content of chest.

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/Winter#57]
The idea with this suggestion is by adding a ``/winter edit`` command, the admin on your server will be able to edit the contents of gift, dated, or timed chest, instead of this being limited to the owner (creator of the chest).

OR

At least some other way of allowing the admin on your server will be able to edit the contents of gift, dated, or timed chest

1) How it would benefit others? (Not just you, but 1,000s of other people using the same plugin.)
When server owners/admin create dated, timied, or gift chests, this command would allow them to edit the contents of such chest, instead of limiting the ability to edit such chest to just the owner of said chest.

2) What would happen if we won't implement this feature? How's your server being affected?
This may result in people seeking out another plugin to use which allows multiple people to edit these types of the chest.

3) If suggesting something new - Can the old system be modified/improved instead?
This is something that could improve the current gift chest types used on this plugin.

**Comment by kangarko** [comment]
Hey!

You can give yourself and staff the "winter.chest.admin" permission, so they will be able to bypass chest restrictions and open locked content:

![img](https://i.imgur.com/xdFVEkZ.png)

**Comment by TheIntolerant** [comment]
Awesome! Thank you for the info!

**Comment by TheIntolerant** [comment]
@kangarko this doesn't seem to work on 1.17.1, unfortunately.

I tried on a prod server but had no luck, so I tested again but on a fresh server (Paper 1.17.1)
``
This server is running Paper version git-Paper-400 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 4ac995a on ver/1.17.1)
You are running the latest version
``

With the following plugins: ``LuckPerms, Tester, Winter``

With the following permission nodes:
```
permissions:
- winter.command.*
- winter.chest.admin
- winter.chest.dated
- winter.chest.gift
- winter.chest.timed
```

And regardless of what I tried, I was unable to allow another user to access a dated or timed chest, etc. To let them make edits to the contents of the chest.

This was regardless if I gave a wildcard perm ``*`` or ``winter.*`` or gave the user OP etc. The chest wasn't accessible to the other user, other than being able to use the chest as normal just like a regular player.

**Comment by TheIntolerant** [comment]
Wait, I think there may have been a slight miscommunication.

So while this does work fine for the ``[Gift]`` chest. I am seeking a way of allowing my admin to edit content inside the ``[Dated]`` or ``[Timed]`` chest. As it stands right now only the creator of the chest, can edit the contents inside of it.

While ``winter.chest.admin`` works for ``[Gift]`` chest, it does NOT work for ``[Dated]`` or ``[Timed]`` chest.

This is where my suggestion to add ``/winter edit`` or a similar command comes into it.

When the creator of a ``[Timed]`` or ``[Dated]`` opens the chest, they get the message "Browsing your own winter chest content..." while for everyone else, it works like a timed or dated chest. 

My suggestion was to make a command to allow extra people (admins or trusted staff etc) to edit the content of this chest (timed or dated chest), instead of limiting the ability to edit the contents of the chest to just the creator of the timed or dated chest.

Hopefully, this makes sense?

**Comment by kangarko** [comment]
I am sorry - I have only tested dated chests, my bad!

Investigating right now.

**Comment by kangarko** [comment]
Fixed. Admins will now be able to open dated/timed chests off limits.

**Comment by TheIntolerant** [comment]
Amazing, thank you so much!
