### ISSUE TITLE
Request for Refund

### ISSUE THREAD

**Issue by kagarins** [kangarko/Winter#6]
Hey Kangarko,

It's really difficult to get ahold of you on spigot, I can't start a conversation with you, nor am I able to leave a message on your profile page, and the "Click Here to send us a message" takes me to this issue page on github, so I guess I'll leave my request here.

Earlier today, I bought the Winter plugin, however, it did not seem to be a fit for my server. Unfortunately, it does not cover areas in snow if there's any obstacles above it, so it looks pretty choppy in a forest region. The same issue with ice-forming occurs, when theres a bridge, or a block above the waters surface, it fails to replace all the water with ice. 

We have unnatural / fake snowy terrain which does not use vanilla biomes and is a server built area, which the plugin's melt feature doesn't seem to support according to the config comments and we also allow players to build / interact with the world so creating a backup and reverting it via world backups isn't an option for us.

Perhaps, those could be suggestions for improvement. I think a lot of what people are looking for is a simple but effective way of covering every block, including tall grass with snow and easily being able to remove it all at a command. 

 I'd like to take advantage of your 14 day refund policy and get a refund for the plugin. Thanks. https://www.spigotmc.org/members/kawaiikamikait.157567/

**Comment by kangarko** [comment]
Refunded, thanks for your feedback.
