### ISSUE TITLE
1.17.1: Snow replaces SNOW_BLOCKs

### ISSUE THREAD

**Issue by radiant-ai** [kangarko/Winter#62]
Generated snow replaces `snow_block`s for some reason and destroys maps built of them. It also replaces existing stacked `snow` blocks increasing the ruination.

**Comment by kangarko** [comment]
I believe it'll be fixed if you place the SNOW_BLOCK material name to the Do_Not_Place_On key (search with CTRL+F) in your settings.yml file

**Comment by radiant-ai** [comment]
> I believe it'll be fixed if you place the SNOW_BLOCK material name to the Do_Not_Place_On key (search with CTRL+F) in your settings.yml file

I already placed `SNOW` into there and it did not help. It was said that it ignores blocks that `contain` that string, so it should've helped me, but it did not.

**Comment by kangarko** [comment]
Set Multi_Layer to false in the next Winter version. I will make snow not being placed above snow_block

**Comment by radiant-ai** [comment]
> Set Multi_Layer to false in the next Winter version. I will make snow not being placed above snow_block

That was already set to false, I had to flip a lot of settings trying to fix my map melting away

**Comment by kangarko** [comment]
Got it, let me know if there's anything else I can help in the current latest version.
