### ISSUE TITLE
MC 1.17.1: Task #403504 for Winter

### ISSUE THREAD

**Issue by ZEROOblivious** [kangarko/Winter#63]
Current Issue:
Console spam every 2 seconds after enabling melt. 
https://pastebin.com/yBAH4TqR

What did we do wrong to cause this spam?
Attaching Config files via Zip Folder. (WinRAR)

Would like to know what we can do to get rid of the console spam? 
We're not seeing much melting either in the process. 

[BugFixRequest.zip](https://github.com/kangarko/Winter/files/7790852/BugFixRequest.zip)

**Comment by kangarko** [comment]
Thanks, will patch. Happy new year!
