### ISSUE TITLE
Feature request: Dated private chests.

### ISSUE THREAD

**Issue by mormoon** [kangarko/Winter#7]
Instead of giving a single chest to 3 different persons, change the dated feature to allow a player to give a private dated chest. This could prove useful for a birthday or Christmas. 

[gift]
[name]
[date]

**Comment by kangarko** [comment]
If I understand correctly, it would only allow 1 player to open the chest at the specified date?

**Comment by mormoon** [comment]
Yes, this would be nice for birthdays or special events. In case if there would be multiple persons involved I would place multiple chests.

**Comment by kangarko** [comment]
I understand, good suggestion I look into it after exams.
