### ISSUE TITLE
1.16.4: Stop snow from accumulating on paths?

### ISSUE THREAD

**Issue by swim709** [kangarko/Winter#8]
I notice the "Do_Not_Place_On" config setting.
Is there a way to configure this so that snow still accumulates on dirt, but not dirt that has been turned into a path with a shovel?

**Comment by ThisIsTenou** [comment]
@brofin The namespaced ID for a path is "grass_path", so if you would add that to the "Do_Not_Place_On"-List, you should be fine - or am I missing something here?

**Comment by swim709** [comment]
> 
> 
> @brofin The namespaced ID for a path is "grass_path", so if you would add that to the "Do_Not_Place_On"-List, you should be fine - or am I missing something here?

Ah ya that should do it. I just wasn't sure what format I needed to put it in. Thanks!
