### ISSUE TITLE
Freezing water causes sugercane to pop

### ISSUE THREAD

**Issue by mormoon** [kangarko/Winter#8]
I know this is "normal" behavior. But this is kinda ruining playermade gardens. Is it possible to implement an option to prevent the sugarcane from despawning?

**Comment by kangarko** [comment]
No sorry this is not possible because it's coming from native Minecraft and Winter cannot see when it's happening. You can disable the freezing feature, though, or just suggest players to place torches or another source of light nearby.

**Comment by kangarko** [comment]
Actually, I have added an option to specify neighbor blocks to not be frozen.
