### ISSUE TITLE
Everyone's gifts could be in a common box, but it would be kinda of an enderchest so you can only see your rewards. 

### ISSUE THREAD

**Issue by CtrlAiDel** [kangarko/Winter#81]
**1) How it would benefit others? (Not just you, but 1,000s of other people using the same plugin.)**
You don't have to create multiple chests for everyone. Just one chest and everyone could get their rewards easily. 

**2) What would happen if we won't implement this feature? How's your server being affected?**
I have CHC but I don't have winter yet. I'm planning to buy it for next season but that was an improvement that i would really have enjoyed in the plugin. I would buy the plugin for sure before winter irl.

**3) If suggesting something new - Can the old system be modified/improved instead?**
I've watched the video description of winter and I don't see any other chest that does the same

I'd like a new type of gift box is possible, that would be kinda like an ender chest for gifts. The admin would pick a rewards/gift that he wants to give to everyone, and a player could only loot the box once per account. So everyone would use the same box.

**Thank you for your plugins**

**Comment by kangarko** [comment]
Hmm I believe we have the Timed Chests that can be looted by every player individually and give each player the same stack of items.
