### ISSUE TITLE
Your Suggestion Title

### ISSUE THREAD

**Issue by wagon9569** [kangarko/Winter#82]
1) How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)
Most builders use a barrier to block players from leaving

2) What would happen if we won't implement this feature? How's your server being affected?
Cannot use it :(

3) If suggesting something new - Can the old system be modified/improved instead?
Yes

```
#Only spawn particles in open arenas?
  Realistic: true
```

Whitelist the block barrier so it can "SNOW" under it.
Or just a list of allowed blocks in the configuration

**Comment by kangarko** [comment]
Amazing suggestion! Will do in 24-48h

**Comment by kangarko** [comment]
Fixed!
