### ISSUE TITLE
1.12.2 Bug

### ISSUE THREAD

**Issue by SladeHazard** [kangarko/Winter#83]
Hey, the latest versions of the plugins never load in 1.12.2 Due to java version not being 17 and another bug is that this option never works on 1.12 server no matter what version of Winter I try:

How strongly should the particles bounce randomly?
Set to 0.8 for thunderstorm-like experience.
  Chaos: 0.8
  
  It does nothing, tested on 3.5.2 and older

**Comment by SladeHazard** [comment]
Another bug is that Gift chests for everyone do not work:

![image](https://github.com/kangarko/Winter/assets/45261094/3f0397eb-02ae-4b28-bf26-cbe204c99ac2)


![image](https://github.com/kangarko/Winter/assets/45261094/3a4d9d1f-73a4-4b92-9624-8f7dbb3630a6)


I put [Gift] on the first line

**Comment by kangarko** [comment]
Thank you.

1. I fixed the Java 1.8 loading on MC 1.12,
2. Unfortunately this option requires a modern Minecraft version.
3. I cannot reproduce. I placed [Gift] on the first line and left the other lines empty, I was able to loot the chest from a secondary account:
![a](https://i.imgur.com/L686jtw.png)

->

![b](https://i.imgur.com/0fj45vI.png)
