### ISSUE TITLE
1.20.2 : Why does snow not fall on the ground?

### ISSUE THREAD

**Issue by D00G3Y** [kangarko/Winter#85]
My server is using a few datapacks to change the world generation from non vanilla biomes. I thought this was the issue until I went into a vanilla biome and snow was not spawning on the ground. 

I haven't tested whether its a version issue with 1.20.2 not being supported. I plan on rolling back to 1.20.1 this weekend. 

Is there another plugin necessary for the snow fall? (Protocol Lib?)

There is no documentation for the Snow part of the plugin on this Github page. Your youtube video has everything, and thats not very accessible.

**Comment by kangarko** [comment]
Have you enabled Terrain.Snow_Generation.Enabled in settings.yml? You can just drop me your full settings.yml so I can review.

Sorry if the video was poorly accessible, not sure what you mean tho, can you please clarify for me? (Not a native English speaker)

**Comment by D00G3Y** [comment]
I must have editied it when the server was live, the changes did not post like I thought they would. I am sorry.

**Comment by kangarko** [comment]
No problem :)
