### ISSUE TITLE
Questions about the Plugin

### ISSUE THREAD

**Issue by JoMiNovi** [kangarko/Winter#87]
Hello,
I'm about to buy this plugin for my SMP server.
So I wanted to know, if it is compatible with Minecraft 1.20.2 and if i can use a Riptide Trident for flying when it's snowing instead of raining.
Best regards,
JoMiNovi.
(Sorry for any language mistakes, I'm german)

**Comment by kangarko** [comment]
Yes it's compatible and yes you can use the riptide trident. Sorry for the late reply.

**Comment by JoMiNovi** [comment]
All good, I already buyed Winter, and I really love it.
Only one more feature would be cool:
If disable-rain is enabled, and it would rain if it isn't, maybe add an option in the config to set an higher amount of snow particles displayed, so it looks like it's snowing more.
Or just an Command for doing so would be fine too, then I can easily make it myself with Skript.

**Comment by kangarko** [comment]
Thank you! For now you can set Weather.Snow_Storm to true and it will show more particles and more chaotically during a thunderstorm.

**Comment by JoMiNovi** [comment]
I already saw that and enabled it, but then I need to enable rain again, and it doesn't look really nice when everywhere on the ground is snow and it rains.

**Comment by kangarko** [comment]
I see, thanks for the suggestion tho, I can have a look when I got more time.
