### ISSUE TITLE
How can I remove all the snow at once please?

### ISSUE THREAD

**Issue by CtrlAiDel** [kangarko/Winter#88]
How can I remove all the snow at once please? 

I tried to close the server, and remove the data.db and restart and it didn't worked. ( I did put back the .db afterward)

I'd like to snow to melt without a player having to "load the chunks".

Thank you, I appreciate your help and your plugins!

**Comment by kangarko** [comment]
Hey,

Sorry for the delay. We have a command called /winter populate which can remove snow in unloaded chunks. For regional removal you can use WorldEdit.

Matej

**Comment by CtrlAiDel** [comment]
Thank you
