### ISSUE TITLE
1.21.1: Snow Not Forming

### ISSUE THREAD

**Issue by RonanHUH** [kangarko/Winter#89]
I loaded up a new world with the winter pluging on spigot. I edited the file to true for the snow generation, and it did not generate snow on the ground. there was an error

it throws:
java.lang.IncompatibleClassChangeError: Found class org.bukkit.block.Biome, but interface was expected

**Comment by kangarko** [comment]
Can you please ensure you are on the very latest version of Winter? If yes, please post me your /winter debug file.

**Comment by RonanHUH** [comment]
[debug.zip](https://github.com/user-attachments/files/17839415/debug.zip)

**Comment by kangarko** [comment]
I apologize, I was sick and still recovering, I'll be dealing with this on Saturday/Sunday, please downgrade for now.

**Comment by kangarko** [comment]
I finally fixed it!! Thank you so much for you patience, the new release will come out tonight.

**Comment by RonanHUH** [comment]
Thank you so much! That was so quick!

**Comment by kangarko** [comment]
Consider giving a review if you enjoy the plugin <3
