### ISSUE TITLE
Particles show up behind water

### ISSUE THREAD

**Issue by PatrickConway76** [kangarko/Winter#9]
When looking at water, the particles seem to show behind water. This is on default minecraft with no shaders or optifine installed.
![2017-11-30_20 57 42](https://user-images.githubusercontent.com/15658900/33466293-8da9e14c-d612-11e7-8f86-3424081d658a.png)

**Comment by kangarko** [comment]
Hey,

thank you for the report, will try to recode the math after exams.

**Comment by mormoon** [comment]
Kinda related, its snowing inside beneath a glas roof.

![2017-12-02_21 01 34](https://user-images.githubusercontent.com/7835585/33519268-0ab142f6-d7a4-11e7-954a-c571bf35f499.png)

**Comment by kangarko** [comment]
Thank you, both issues were fixed in the next release. The first issue was partially fixed so the particles don't generate right above the water, and the second was completely fixed.
