### ISSUE TITLE
Water flowing down besides fields is still being freezed

### ISSUE THREAD

**Issue by ThisIsTenou** [kangarko/Winter#9]
I'd love to have a "range"-setting for freezing water near crops.

A couple users complained about their farms not working anymore, as water flowing down besides crops will eventually, when dropping down by one block, freeze as the one water-block on the step is not right near to a crop.

![2020-12-02_08 27 30](https://user-images.githubusercontent.com/57889616/100842924-de49d580-3479-11eb-89a7-7d434e1c152a.png)

It'd be great to have the option of defining a range (both horizontal as vertical) for water to not freeze around crops, to assure that farms still work.

**Comment by kangarko** [comment]
Thank you for suggesting this. When I have time to code a more advanced algorithm to catch this I may push an update 👍
