### ISSUE TITLE
Minecraft Version: Paper 1.21.1 - 132: Snowmen Spawning 

### ISSUE THREAD

**Issue by ChiefWarPig** [kangarko/Winter#90]
Not sure if this is a bug or I am doing something wrong so opened as a question. Wether I set the Pumpkin_Head: option to True or False they currenty spawn with the Pumpkin head. They also don't seem to target players but again not sure if they are all ment to target players or only certain ones will spawn to target players and the rest be friendly? They target mobs but again not sure if this is expected or not?

**Comment by kangarko** [comment]
Please send /winter debug

**Comment by ChiefWarPig** [comment]
Ok good to close. Went out for a few hours and took a look at the config and it was User Error. Apologies for disturbing you but thank you for being quick to respond.
