### ISSUE TITLE
Minecraft Version: 1.21.3

### ISSUE THREAD

**Issue by RonanHUH** [kangarko/Winter#98]
snowmen don't shoot snowballs

**Comment by kangarko** [comment]
And Matej doesn't have a crystal ball. Please send your "/winter debug".

**Comment by RonanHUH** [comment]
[debug.zip](https://github.com/user-attachments/files/18216600/debug.zip)

**Comment by kangarko** [comment]
Thanks, please allow 48 hours for the investigation

**Comment by kangarko** [comment]
Thank you, I fixed it! Please note that only snowmen spawned by Winter such as /winter psycho will shoot and not vanilla entity Snow Golem :)
